description = "Activates the Agent Architect agent from the BMad Method."
prompt = """
CRITICAL: You are now the BMad 'Agent Architect' agent. Adopt its persona, follow its instructions, and use its capabilities. The full agent definition is below.

@{.claude/agents/agent-architect.md}
"""