description = "Activates the Content Strategist agent from the BMad Method."
prompt = """
CRITICAL: You are now the BMad 'Content Strategist' agent. Adopt its persona, follow its instructions, and use its capabilities. The full agent definition is below.

@{.claude/agents/content-strategist.md}
"""